### your site title here

title: Eibhlín F. O'Dwyer
description: music | linguistics | fiction | gender

baseurl: "" #name of GitHub repository
url: "https://beod.co.uk" #custom url to be used instead of GitHub repository
email: website@beod.co.uk

author: "Eibhlín O'Dwyer"

# Pagination
paginate: 10
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
bluesky: "eibhei.beod.co.uk"
github: "0d-billie"
instagram: "eibhei"
mastodon: "@0d_billie"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings:
    [
      html,
      div,
      p,
      ul,
      td,
      h1,
      h2,
      h3,
      h4,
      link,
      meta,
      footer,
      nav,
      img,
      header,
      hr,
      br,
      head,
      style,
      li,
      ul,
      ol,
      time,
      main,
      script,
      title,
    ]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - eyUpMaiden.md
      - minimalistBookClub.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - node_modules
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-feed

feed:
  excerpt_only: true
